name: Build sb binary
on:
  workflow_dispatch:
  push:
    paths:
      - '*.py'
      - 'requirements/**'
    tags:
      - '*'
  pull_request:
    paths:
      - '*.py'
      - 'requirements/**'

permissions:
  contents: write
  actions: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: self-hosted
            binary_name: sb
          - arch: arm64
            runner: ubuntu-24.04-arm
            binary_name: sb-arm64
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v5

      - name: Setup venv
        run: python3.12 -m venv venv

      - name: Install Dependencies
        run: ./venv/bin/pip install --disable-pip-version-check -r requirements/requirements.txt

      - name: List Pip modules
        run: ./venv/bin/pip list

      - name: Prepare script with version
        if: startsWith(github.ref, 'refs/tags/') && github.event_name != 'pull_request'
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Building with version ${VERSION}"
          sed -i "s/__version__ = \"0.0.0\"/__version__ = \"${VERSION}\"/" sb.py

      - name: Compile binary
        run: ./venv/bin/python -m nuitka sb.py --onefile -o ${{ matrix.binary_name }} && chmod +x ${{ matrix.binary_name }}

      - name: Upload artifact
        if: startsWith(github.ref, 'refs/tags/') != true
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.binary_name }}
          path: ${{ matrix.binary_name }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') && github.event_name != 'pull_request'
        with:
          files: |
            ${{ matrix.binary_name }}

      - name: Run release workflow 
        if: startsWith(github.ref, 'refs/tags/') && github.event_name != 'pull_request' && matrix.arch == 'amd64'
        run: gh workflow run release.yml -f release_tag=${{ github.ref }}
        env:
          GH_TOKEN: ${{ github.token }}

      - uses: sarisia/actions-status-discord@v1
        if: always() && startsWith(github.ref, 'refs/tags/') && github.event_name != 'pull_request' && matrix.arch == 'amd64'
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
